; fpsp_lib.s -- GENERATED by tb/mk_fpsp.py; edit that, not this.
;
; Motorola's M68040 FPSP, exactly as Thomas Richter's 68040.library 40.2
; (MMULib) carries it, installed by the library's own code, runs the
; floating-point instructions a 68040 does not implement.  mk_fpsplib.py
; relocates the library to $10000 (code) / $1A000 (data); this program
; builds a minimal ExecBase (Supervisor, Alert, CacheClearU, AttnFlags) and
; a library base, calls the library's installer at code+$520, checks the
; vectors it wrote, drops to USER mode and runs the cases.  Expected values:
; mk_fpsp.py (mpmath at 300 bits, the FPSP model, Motorola's tables).
;
; diff: --cycles 4000000
v_flin	equ	unexp
v_ill	equ	unexp
v_adr	equ	unexp
v_alin	equ	unexp
v_prv	equ	unexp
v_fmt	equ	unexp
v_trp0	equ	unexp
	include	"../pipe_asm/vectors.inc"
	include	"../build/fpsp040lib.inc"

EXECBASE equ	$1C400
LIBBASE	equ	$1B000
SSP_TOP	equ	$3F000
USP_TOP	equ	$3E000

	org	$400
start:
	bra.w	main
halt:
	bra.s	halt			; $404: the bench stops when this retires
main:
	lea	SSP_TOP,sp
	lea	EXECBASE,a0
	move.w	#$4EF9,-$1E(a0)		; Supervisor()
	move.l	#x_super,-$1C(a0)
	move.w	#$4EF9,-$6C(a0)		; Alert()
	move.l	#x_alert,-$6A(a0)
	move.w	#$4EF9,-$27C(a0)	; CacheClearU()
	move.l	#x_rts,-$27A(a0)
	move.b	#$4F,$129(a0)		; AttnFlags: 010/020/030/040 + FPU40, no 68881/2
	lea	LIBBASE,a6
	move.l	a0,$30(a6)		; lib_SysBase
	clr.b	$22(a6)			; FPUControl flags: every FPSP path on
	move.l	a0,LIB_SYSBASE		; the handlers' SysBase (code+$330 does this)
	jsr	LIB_INSTALL		; the library's own FPSP installer
	lea	EXECBASE,a0		; (the installer used a0 for the VBR)
	move.b	$129(a0),$7010		; AttnFlags afterwards: 68881/2 now claimed
	move.l	$2C,$7014			; vector 11
	move.l	$DC,$7018			; vector 55
	move.l	$C4,$701c			; vector 49
	lea	USP_TOP,a0
	move.l	a0,usp
	move.w	#$0000,sr		; USER mode from here on


;----------------------------------------------------------- pass A
	fmove.l	#0,fpcr
	fmove.l	#0,fpsr
	fmove.x	$28000,fp0
	fsin.x	fp0,fp1		; fsin(0.5)
	fmove.l	fpsr,$2000c
	fmove.x	fp1,$20000
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fsin.x	$2800c,fp1		; fsin(1.0), extended memory source
	fmove.l	fpsr,$2001c
	fmove.x	fp1,$20010
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548E,$C004,$0000,$0000,$0000	; fsin(-2.5), double immediate
	fmove.l	fpsr,$2002c
	fmove.x	fp1,$20020
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28024,fp0
	fsin.x	fp0,fp1		; fsin(100.0)
	fmove.l	fpsr,$2003c
	fmove.x	fp1,$20030
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fsin.x	$28030,fp1		; fsin(1e-5), extended memory source
	fmove.l	fpsr,$2004c
	fmove.x	fp1,$20040
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$549D,$3FE0,$0000,$0000,$0000	; fcos(0.5), double immediate
	fmove.l	fpsr,$2005c
	fmove.x	fp1,$20050
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28048,fp0
	fcos.x	fp0,fp1		; fcos(2.0)
	fmove.l	fpsr,$2006c
	fmove.x	fp1,$20060
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fcos.x	$28054,fp1		; fcos(1000.0), extended memory source
	fmove.l	fpsr,$2007c
	fmove.x	fp1,$20070
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548F,$3FE0,$0000,$0000,$0000	; ftan(0.5), double immediate
	fmove.l	fpsr,$2008c
	fmove.x	fp1,$20080
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$2806c,fp0
	ftan.x	fp0,fp1		; ftan(1.2)
	fmove.l	fpsr,$2009c
	fmove.x	fp1,$20090
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fasin.x	$28078,fp1		; fasin(0.5), extended memory source
	fmove.l	fpsr,$200ac
	fmove.x	fp1,$200a0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$549C,$3FD3,$3333,$3333,$3333	; facos(0.3), double immediate
	fmove.l	fpsr,$200bc
	fmove.x	fp1,$200b0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28090,fp0
	fatan.x	fp0,fp1		; fatan(2.0)
	fmove.l	fpsr,$200cc
	fmove.x	fp1,$200c0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fatan.x	$2809c,fp1		; fatan(-0.5), extended memory source
	fmove.l	fpsr,$200dc
	fmove.x	fp1,$200d0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5482,$3FF8,$0000,$0000,$0000	; fsinh(1.5), double immediate
	fmove.l	fpsr,$200ec
	fmove.x	fp1,$200e0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$280b4,fp0
	fcosh.x	fp0,fp1		; fcosh(1.5)
	fmove.l	fpsr,$200fc
	fmove.x	fp1,$200f0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	ftanh.x	$280c0,fp1		; ftanh(0.8), extended memory source
	fmove.l	fpsr,$2010c
	fmove.x	fp1,$20100
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548D,$3FE0,$0000,$0000,$0000	; fatanh(0.5), double immediate
	fmove.l	fpsr,$2011c
	fmove.x	fp1,$20110
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$280d8,fp0
	fetox.x	fp0,fp1		; fetox(1.0)
	fmove.l	fpsr,$2012c
	fmove.x	fp1,$20120
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fetox.x	$280e4,fp1		; fetox(-3.5), extended memory source
	fmove.l	fpsr,$2013c
	fmove.x	fp1,$20130
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5490,$4024,$0000,$0000,$0000	; fetox(10.0), double immediate
	fmove.l	fpsr,$2014c
	fmove.x	fp1,$20140
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$280fc,fp0
	fetoxm1.x	fp0,fp1		; fetoxm1(1e-3)
	fmove.l	fpsr,$2015c
	fmove.x	fp1,$20150
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fetoxm1.x	$28108,fp1		; fetoxm1(0.5), extended memory source
	fmove.l	fpsr,$2016c
	fmove.x	fp1,$20160
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5491,$400A,$6666,$6666,$6666	; ftwotox(3.3), double immediate
	fmove.l	fpsr,$2017c
	fmove.x	fp1,$20170
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28120,fp0
	ftentox.x	fp0,fp1		; ftentox(2.5)
	fmove.l	fpsr,$2018c
	fmove.x	fp1,$20180
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	flogn.x	$2812c,fp1		; flogn(2.0), extended memory source
	fmove.l	fpsr,$2019c
	fmove.x	fp1,$20190
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5494,$4024,$0000,$0000,$0000	; flogn(10.0), double immediate
	fmove.l	fpsr,$201ac
	fmove.x	fp1,$201a0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28144,fp0
	flogn.x	fp0,fp1		; flogn(0.3)
	fmove.l	fpsr,$201bc
	fmove.x	fp1,$201b0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	flognp1.x	$28150,fp1		; flognp1(1e-4), extended memory source
	fmove.l	fpsr,$201cc
	fmove.x	fp1,$201c0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5486,$3FF8,$0000,$0000,$0000	; flognp1(1.5), double immediate
	fmove.l	fpsr,$201dc
	fmove.x	fp1,$201d0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28168,fp0
	flog10.x	fp0,fp1		; flog10(1000.0)
	fmove.l	fpsr,$201ec
	fmove.x	fp1,$201e0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	flog10.x	$28174,fp1		; flog10(7.0), extended memory source
	fmove.l	fpsr,$201fc
	fmove.x	fp1,$201f0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5496,$4020,$0000,$0000,$0000	; flog2(8.0), double immediate
	fmove.l	fpsr,$2020c
	fmove.x	fp1,$20200
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$2818c,fp0
	flog2.x	fp0,fp1		; flog2(3.0)
	fmove.l	fpsr,$2021c
	fmove.x	fp1,$20210
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fgetexp.x	$28198,fp1		; fgetexp(1000.0), extended memory source
	fmove.l	fpsr,$2022c
	fmove.x	fp1,$20220
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$549F,$408F,$4000,$0000,$0000	; fgetman(1000.0), double immediate
	fmove.l	fpsr,$2023c
	fmove.x	fp1,$20230
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$281b0,fp0
	fgetexp.x	fp0,fp1		; fgetexp(-0.1)
	fmove.l	fpsr,$2024c
	fmove.x	fp1,$20240
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fgetman.x	$281bc,fp1		; fgetman(-0.1), extended memory source
	fmove.l	fpsr,$2025c
	fmove.x	fp1,$20250
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5481,$4004,$0000,$0000,$0000	; fint(2.5), double immediate
	fmove.l	fpsr,$2026c
	fmove.x	fp1,$20260
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$281d4,fp0
	fint.x	fp0,fp1		; fint(-3.7)
	fmove.l	fpsr,$2027c
	fmove.x	fp1,$20270
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fint.x	$281e0,fp1		; fint(3.5), extended memory source
	fmove.l	fpsr,$2028c
	fmove.x	fp1,$20280
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5483,$C00D,$9999,$9999,$999A	; fintrz(-3.7), double immediate
	fmove.l	fpsr,$2029c
	fmove.x	fp1,$20290
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$281f8,fp0
	fintrz.x	fp0,fp1		; fintrz(5.99)
	fmove.l	fpsr,$202ac
	fmove.x	fp1,$202a0
	addq.l	#1,$700c

; FSINCOS: cos to FPc, sin to FPs
	fmove.l	#0,fpsr
	fmove.x	$28204,fp0
	fsincos.x	fp0,fp2:fp1
	fmove.l	fpsr,$202bc
	fmove.x	fp1,$202b0
	addq.l	#1,$700c
	fmove.x	fp2,$202c0

; the dyadic ones: dest op src
	fmove.l	#0,fpsr
	fmove.x	$28210,fp1
	fmove.x	$2821c,fp0
	fmod.x	fp0,fp1		; fmod(10.0, 3.0)
	fmove.l	fpsr,$202dc
	fmove.x	fp1,$202d0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28228,fp1
	fmove.x	$28234,fp0
	fmod.x	fp0,fp1		; fmod(-7.5, 2.0)
	fmove.l	fpsr,$202ec
	fmove.x	fp1,$202e0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28240,fp1
	fmove.x	$2824c,fp0
	fmod.x	fp0,fp1		; fmod(100.25, 0.75)
	fmove.l	fpsr,$202fc
	fmove.x	fp1,$202f0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28258,fp1
	fmove.x	$28264,fp0
	frem.x	fp0,fp1		; frem(10.0, 3.0)
	fmove.l	fpsr,$2030c
	fmove.x	fp1,$20300
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28270,fp1
	fmove.x	$2827c,fp0
	frem.x	fp0,fp1		; frem(11.0, 3.0)
	fmove.l	fpsr,$2031c
	fmove.x	fp1,$20310
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28288,fp1
	fmove.x	$28294,fp0
	frem.x	fp0,fp1		; frem(-7.5, 2.0)
	fmove.l	fpsr,$2032c
	fmove.x	fp1,$20320
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$282a0,fp1
	fmove.x	$282ac,fp0
	fscale.x	fp0,fp1		; fscale(1.5, 3.0)
	fmove.l	fpsr,$2033c
	fmove.x	fp1,$20330
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$282b8,fp1
	fmove.x	$282c4,fp0
	fscale.x	fp0,fp1		; fscale(-5.0, -2.0)
	fmove.l	fpsr,$2034c
	fmove.x	fp1,$20340
	addq.l	#1,$700c

; FMOVECR: the constant ROM (the 68040 traps every offset to the FPSP)
	fmove.l	#0,fpsr
	fmovecr.x	#$00,fp1
	fmove.l	fpsr,$2035c
	fmove.x	fp1,$20350
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$0b,fp1
	fmove.l	fpsr,$2036c
	fmove.x	fp1,$20360
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$0c,fp1
	fmove.l	fpsr,$2037c
	fmove.x	fp1,$20370
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$0d,fp1
	fmove.l	fpsr,$2038c
	fmove.x	fp1,$20380
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$0e,fp1
	fmove.l	fpsr,$2039c
	fmove.x	fp1,$20390
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$0f,fp1
	fmove.l	fpsr,$203ac
	fmove.x	fp1,$203a0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$30,fp1
	fmove.l	fpsr,$203bc
	fmove.x	fp1,$203b0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$31,fp1
	fmove.l	fpsr,$203cc
	fmove.x	fp1,$203c0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$32,fp1
	fmove.l	fpsr,$203dc
	fmove.x	fp1,$203d0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$33,fp1
	fmove.l	fpsr,$203ec
	fmove.x	fp1,$203e0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$3a,fp1
	fmove.l	fpsr,$203fc
	fmove.x	fp1,$203f0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmovecr.x	#$3b,fp1
	fmove.l	fpsr,$2040c
	fmove.x	fp1,$20400
	addq.l	#1,$700c

; (An)+ and -(An): the 68040 has already stepped An when the FPSP runs
	movea.l	#$282d0,a2
	fmove.l	#0,fpsr
	fetox.x	(a2)+,fp1
	move.l	a2,$7020
	fmove.l	fpsr,$2041c
	fmove.x	fp1,$20410
	addq.l	#1,$700c
	movea.l	#$282e8,a3
	fmove.l	#0,fpsr
	flogn.x	-(a3),fp1
	move.l	a3,$7024
	fmove.l	fpsr,$2042c
	fmove.x	fp1,$20420
	addq.l	#1,$700c

; integer, single and word sources, converted by the hardware before the trap
	fmove.l	#0,fpsr
	dc.w	$F23C,$4095,$0001,$86A0	; flog10.l #100000,fp1
	fmove.l	fpsr,$2043c
	fmove.x	fp1,$20430
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$4490,$3F00,$0000	; fetox.s #0.5,fp1
	fmove.l	fpsr,$2044c
	fmove.x	fp1,$20440
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5091,$FFFD	; ftwotox.w #-3,fp1
	fmove.l	fpsr,$2045c
	fmove.x	fp1,$20450
	addq.l	#1,$700c

;----------------------------------------------------------- pass U
; unsupported data types (vector 55): packed decimal, denormals
	fmove.l	#0,fpsr
	dc.w	$F23C,$4C80,$0002,$0001,$2500,$0000,$0000,$0000	; fmove.p #1.25E+2,fp1
	fmove.l	fpsr,$2046c
	fmove.x	fp1,$20460
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$4C80,$C001,$0003,$7500,$0000,$0000,$0000	; fmove.p #-3.75E-1,fp1
	fmove.l	fpsr,$2047c
	fmove.x	fp1,$20470
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$4C80,$0010,$0001,$5000,$0000,$0000,$0000	; fmove.p #1.5E+10,fp1
	fmove.l	fpsr,$2048c
	fmove.x	fp1,$20480
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.p	$282e8,fp1		; 3.1415926535897932E+0 from memory
	fmove.l	fpsr,$2049c
	fmove.x	fp1,$20490
	addq.l	#1,$700c
	fmove.x	$282f4,fp1
	fmove.l	#0,fpsr
	fmove.p	fp1,$2c000{#3}	; fmove.p 125.0{#3}
	addq.l	#1,$700c
	fmove.x	$28300,fp1
	fmove.l	#0,fpsr
	fmove.p	fp1,$2c00c{#2}	; fmove.p -0.375{#2}
	addq.l	#1,$700c
	fmove.x	$2830c,fp1
	fmove.l	#0,fpsr
	fmove.p	fp1,$2c018{#1}	; fmove.p 1.0{#1}
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28318,fp1		; an extended denormal into a register
	fmove.l	fpsr,$204ac
	fmove.x	fp1,$204a0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28318,fp1
	dc.w	$F23C,$48A3,$406B,$0000,$8000,$0000,$0000,$0000	; fmul.x #2^108,fp1 -- a denormal register operand
	fmove.l	fpsr,$204bc
	fmove.x	fp1,$204b0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28324,fp1
	dc.w	$F23C,$54A3,$0000,$0000,$0000,$0001	; fmul.d #2^-1074,fp1 -- a double denormal source
	fmove.l	fpsr,$204cc
	fmove.x	fp1,$204c0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$4480,$0040,$0000	; fmove.s #2^-127,fp1 -- a single denormal source
	fmove.l	fpsr,$204dc
	fmove.x	fp1,$204d0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	fmove.x	$28318,fp1
	dc.w	$F23C,$48A2,$0000,$0000,$0000,$0000,$0000,$0000	; fadd.x #0,fp1 -- denormal + 0
	fmove.l	fpsr,$204ec
	fmove.x	fp1,$204e0
	addq.l	#1,$700c

;----------------------------------------------------------- pass B
	fmove.l	#$80,fpcr		; round to double, nearest
	fmove.l	#0,fpsr
	dc.w	$F23C,$548E,$3FE0,$0000,$0000,$0000	; fsin(0.5)
	fmove.l	fpsr,$24008
	fmove.d	fp1,$24000
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548E,$3FF0,$0000,$0000,$0000	; fsin(1.0)
	fmove.l	fpsr,$24014
	fmove.d	fp1,$2400c
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548E,$C004,$0000,$0000,$0000	; fsin(-2.5)
	fmove.l	fpsr,$24020
	fmove.d	fp1,$24018
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548E,$4059,$0000,$0000,$0000	; fsin(100.0)
	fmove.l	fpsr,$2402c
	fmove.d	fp1,$24024
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548E,$3EE4,$F8B5,$88E3,$68F1	; fsin(1e-5)
	fmove.l	fpsr,$24038
	fmove.d	fp1,$24030
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$549D,$3FE0,$0000,$0000,$0000	; fcos(0.5)
	fmove.l	fpsr,$24044
	fmove.d	fp1,$2403c
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$549D,$4000,$0000,$0000,$0000	; fcos(2.0)
	fmove.l	fpsr,$24050
	fmove.d	fp1,$24048
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$549D,$408F,$4000,$0000,$0000	; fcos(1000.0)
	fmove.l	fpsr,$2405c
	fmove.d	fp1,$24054
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548F,$3FE0,$0000,$0000,$0000	; ftan(0.5)
	fmove.l	fpsr,$24068
	fmove.d	fp1,$24060
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548F,$3FF3,$3333,$3333,$3333	; ftan(1.2)
	fmove.l	fpsr,$24074
	fmove.d	fp1,$2406c
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548C,$3FE0,$0000,$0000,$0000	; fasin(0.5)
	fmove.l	fpsr,$24080
	fmove.d	fp1,$24078
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$549C,$3FD3,$3333,$3333,$3333	; facos(0.3)
	fmove.l	fpsr,$2408c
	fmove.d	fp1,$24084
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548A,$4000,$0000,$0000,$0000	; fatan(2.0)
	fmove.l	fpsr,$24098
	fmove.d	fp1,$24090
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548A,$BFE0,$0000,$0000,$0000	; fatan(-0.5)
	fmove.l	fpsr,$240a4
	fmove.d	fp1,$2409c
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5482,$3FF8,$0000,$0000,$0000	; fsinh(1.5)
	fmove.l	fpsr,$240b0
	fmove.d	fp1,$240a8
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5499,$3FF8,$0000,$0000,$0000	; fcosh(1.5)
	fmove.l	fpsr,$240bc
	fmove.d	fp1,$240b4
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5489,$3FE9,$9999,$9999,$999A	; ftanh(0.8)
	fmove.l	fpsr,$240c8
	fmove.d	fp1,$240c0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$548D,$3FE0,$0000,$0000,$0000	; fatanh(0.5)
	fmove.l	fpsr,$240d4
	fmove.d	fp1,$240cc
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5490,$3FF0,$0000,$0000,$0000	; fetox(1.0)
	fmove.l	fpsr,$240e0
	fmove.d	fp1,$240d8
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5490,$C00C,$0000,$0000,$0000	; fetox(-3.5)
	fmove.l	fpsr,$240ec
	fmove.d	fp1,$240e4
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5490,$4024,$0000,$0000,$0000	; fetox(10.0)
	fmove.l	fpsr,$240f8
	fmove.d	fp1,$240f0
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5488,$3F50,$624D,$D2F1,$A9FC	; fetoxm1(1e-3)
	fmove.l	fpsr,$24104
	fmove.d	fp1,$240fc
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5488,$3FE0,$0000,$0000,$0000	; fetoxm1(0.5)
	fmove.l	fpsr,$24110
	fmove.d	fp1,$24108
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5491,$400A,$6666,$6666,$6666	; ftwotox(3.3)
	fmove.l	fpsr,$2411c
	fmove.d	fp1,$24114
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5492,$4004,$0000,$0000,$0000	; ftentox(2.5)
	fmove.l	fpsr,$24128
	fmove.d	fp1,$24120
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5494,$4000,$0000,$0000,$0000	; flogn(2.0)
	fmove.l	fpsr,$24134
	fmove.d	fp1,$2412c
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5494,$4024,$0000,$0000,$0000	; flogn(10.0)
	fmove.l	fpsr,$24140
	fmove.d	fp1,$24138
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5494,$3FD3,$3333,$3333,$3333	; flogn(0.3)
	fmove.l	fpsr,$2414c
	fmove.d	fp1,$24144
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5486,$3F1A,$36E2,$EB1C,$432D	; flognp1(1e-4)
	fmove.l	fpsr,$24158
	fmove.d	fp1,$24150
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5486,$3FF8,$0000,$0000,$0000	; flognp1(1.5)
	fmove.l	fpsr,$24164
	fmove.d	fp1,$2415c
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5495,$408F,$4000,$0000,$0000	; flog10(1000.0)
	fmove.l	fpsr,$24170
	fmove.d	fp1,$24168
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5495,$401C,$0000,$0000,$0000	; flog10(7.0)
	fmove.l	fpsr,$2417c
	fmove.d	fp1,$24174
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5496,$4020,$0000,$0000,$0000	; flog2(8.0)
	fmove.l	fpsr,$24188
	fmove.d	fp1,$24180
	addq.l	#1,$700c
	fmove.l	#0,fpsr
	dc.w	$F23C,$5496,$4008,$0000,$0000,$0000	; flog2(3.0)
	fmove.l	fpsr,$24194
	fmove.d	fp1,$2418c
	addq.l	#1,$700c
	fmove.l	#0,fpcr

	move.l	#$600D,$7028
	bra.w	halt

; exec.library Supervisor(): the routine at a5 ends in RTE
x_super:
	move.w	#0,-(sp)		; format $0
	pea	x_rts(pc)
	move.w	sr,-(sp)
	jmp	(a5)
x_rts:
	rts

; exec.library Alert(): the FPSP met a frame it cannot handle
x_alert:
	move.l	d7,$7008
	bra.w	halt

unexp:
	move.w	6(sp),$7002		; format/vector of the stray exception
	move.l	2(sp),$7004		; and its PC
	bra.w	halt


	org	$28000
	dc.l	$3ffe0000,$80000000,$00000000
	dc.l	$3fff0000,$80000000,$00000000
	dc.l	$c0000000,$a0000000,$00000000
	dc.l	$40050000,$c8000000,$00000000
	dc.l	$3fee0000,$a7c5ac47,$1b478800
	dc.l	$3ffe0000,$80000000,$00000000
	dc.l	$40000000,$80000000,$00000000
	dc.l	$40080000,$fa000000,$00000000
	dc.l	$3ffe0000,$80000000,$00000000
	dc.l	$3fff0000,$99999999,$99999800
	dc.l	$3ffe0000,$80000000,$00000000
	dc.l	$3ffd0000,$99999999,$99999800
	dc.l	$40000000,$80000000,$00000000
	dc.l	$bffe0000,$80000000,$00000000
	dc.l	$3fff0000,$c0000000,$00000000
	dc.l	$3fff0000,$c0000000,$00000000
	dc.l	$3ffe0000,$cccccccc,$ccccd000
	dc.l	$3ffe0000,$80000000,$00000000
	dc.l	$3fff0000,$80000000,$00000000
	dc.l	$c0000000,$e0000000,$00000000
	dc.l	$40020000,$a0000000,$00000000
	dc.l	$3ff50000,$83126e97,$8d4fe000
	dc.l	$3ffe0000,$80000000,$00000000
	dc.l	$40000000,$d3333333,$33333000
	dc.l	$40000000,$a0000000,$00000000
	dc.l	$40000000,$80000000,$00000000
	dc.l	$40020000,$a0000000,$00000000
	dc.l	$3ffd0000,$99999999,$99999800
	dc.l	$3ff10000,$d1b71758,$e2196800
	dc.l	$3fff0000,$c0000000,$00000000
	dc.l	$40080000,$fa000000,$00000000
	dc.l	$40010000,$e0000000,$00000000
	dc.l	$40020000,$80000000,$00000000
	dc.l	$40000000,$c0000000,$00000000
	dc.l	$40080000,$fa000000,$00000000
	dc.l	$40080000,$fa000000,$00000000
	dc.l	$bffb0000,$cccccccc,$ccccd000
	dc.l	$bffb0000,$cccccccc,$ccccd000
	dc.l	$40000000,$a0000000,$00000000
	dc.l	$c0000000,$eccccccc,$ccccd000
	dc.l	$40000000,$e0000000,$00000000
	dc.l	$c0000000,$eccccccc,$ccccd000
	dc.l	$40010000,$bfae147a,$e147b000
	dc.l	$3ffe0000,$b3333333,$33333000
	dc.l	$40020000,$a0000000,$00000000
	dc.l	$40000000,$c0000000,$00000000
	dc.l	$c0010000,$f0000000,$00000000
	dc.l	$40000000,$80000000,$00000000
	dc.l	$40050000,$c8800000,$00000000
	dc.l	$3ffe0000,$c0000000,$00000000
	dc.l	$40020000,$a0000000,$00000000
	dc.l	$40000000,$c0000000,$00000000
	dc.l	$40020000,$b0000000,$00000000
	dc.l	$40000000,$c0000000,$00000000
	dc.l	$c0010000,$f0000000,$00000000
	dc.l	$40000000,$80000000,$00000000
	dc.l	$3fff0000,$c0000000,$00000000
	dc.l	$40000000,$c0000000,$00000000
	dc.l	$c0010000,$a0000000,$00000000
	dc.l	$c0000000,$80000000,$00000000
	dc.l	$3ffd0000,$80000000,$00000000
	dc.l	$3ffe0000,$c0000000,$00000000
	dc.l	$00000003,$14159265,$35897932
	dc.l	$40050000,$fa000000,$00000000
	dc.l	$bffd0000,$c0000000,$00000000
	dc.l	$3fff0000,$80000000,$00000000
	dc.l	$00000000,$00000000,$00000100
	dc.l	$43e70000,$80000000,$00000000

	org	LIB_CODE
	incbin	"../build/fpsp040lib.bin"
