; chk.s - plan M3 tb_ap040_pipe_chk: CHK.W/.L (N tracks the sign, Z C V undefined -> as the reference), CHK2/CMP2 .B/.W/.L signed and wrapped bounds, An with sign-extended bounds, TRAPV, TRAPcc / TRAPcc.W / TRAPcc.L; vectors 6 and 7, format $2, stacked PC = the next instruction, address = the trapping one (M68040UM 8.2.3 p. 8-8).
; Generated by findings/ap040-pipelined/tests/mk_m3progs.py; expect file from the reference.
; diff: --cycles 200000
; expect-inimage
; expect-range: 8000 8a7c
v_adr	equ	unexp
v_ill	equ	unexp
v_prv	equ	unexp
v_alin	equ	unexp
v_flin	equ	unexp
v_fmt	equ	unexp
v_trp0	equ	unexp
v_chk	equ	trap_h
v_trapv	equ	trap_h
	include	"vectors.inc"

	org	$400
start:
	movea.l	#$8000,a6
	movea.l	#$7F00,a5
	move.l	#$00000000,d1
	move.l	#$00000100,d2
	move.w	#$1F,ccr
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00000100,d1
	move.l	#$00000100,d2
	move.w	#$1F,ccr
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00000101,d1
	move.l	#$00000100,d2
	move.w	#$1F,ccr
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$0000ffff,d1
	move.l	#$00000100,d2
	move.w	#$1F,ccr
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00007fff,d1
	move.l	#$00000100,d2
	move.w	#$1F,ccr
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00000080,d1
	move.l	#$00000100,d2
	move.w	#$1F,ccr
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00000000,d1
	move.l	#$00010000,d2
	move.w	#$1F,ccr
	chk.l	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00010000,d1
	move.l	#$00010000,d2
	move.w	#$1F,ccr
	chk.l	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00010001,d1
	move.l	#$00010000,d2
	move.w	#$1F,ccr
	chk.l	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$ffffffff,d1
	move.l	#$00010000,d2
	move.w	#$1F,ccr
	chk.l	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$80000000,d1
	move.l	#$00010000,d2
	move.w	#$1F,ccr
	chk.l	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$00000005,d1
	move.l	#$00010000,d2
	move.w	#$1F,ccr
	chk.l	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$FFFF,d2
	moveq	#0,d1
	move.w	#$00,ccr
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.b	#$10,(a5)
	move.b	#$20,1(a5)
	move.l	#$A5A5A5A5,d1
	move.b	#$f,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$f,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$10,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$10,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$15,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$15,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$20,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$20,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$21,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$21,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$90,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$90,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.b	#$f0,(a5)
	move.b	#$10,1(a5)
	move.l	#$A5A5A5A5,d1
	move.b	#$ef,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$ef,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$f0,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$f0,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$0,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$0,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$10,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$10,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$11,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$11,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$80,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$80,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.b	#$20,(a5)
	move.b	#$10,1(a5)
	move.l	#$A5A5A5A5,d1
	move.b	#$5,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$5,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$10,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$10,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$15,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$15,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$20,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$20,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$25,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$25,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$90,d1
	move.w	#$1F,ccr
	cmp2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.b	#$90,d1
	move.w	#$1F,ccr
	chk2.b	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.w	#$8000,(a5)
	move.w	#$7fff,2(a5)
	move.l	#$A5A5A5A5,d1
	move.w	#$0,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$0,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$8000,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$8000,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$7fff,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$7fff,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	movea.l	#$ffff8000,a1
	move.w	#$1F,ccr
	chk2.w	(a5),a1
	nop
	move.w	ccr,(a6)+
	movea.l	#$00007fff,a1
	move.w	#$1F,ccr
	chk2.w	(a5),a1
	nop
	move.w	ccr,(a6)+
	movea.l	#$00008000,a1
	move.w	#$1F,ccr
	chk2.w	(a5),a1
	nop
	move.w	ccr,(a6)+
	move.w	#$100,(a5)
	move.w	#$200,2(a5)
	move.l	#$A5A5A5A5,d1
	move.w	#$ff,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$ff,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$100,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$100,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$180,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$180,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$200,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$200,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$201,d1
	move.w	#$1F,ccr
	cmp2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A5A5,d1
	move.w	#$201,d1
	move.w	#$1F,ccr
	chk2.w	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	movea.l	#$ffff8000,a1
	move.w	#$1F,ccr
	chk2.w	(a5),a1
	nop
	move.w	ccr,(a6)+
	movea.l	#$00007fff,a1
	move.w	#$1F,ccr
	chk2.w	(a5),a1
	nop
	move.w	ccr,(a6)+
	movea.l	#$00008000,a1
	move.w	#$1F,ccr
	chk2.w	(a5),a1
	nop
	move.w	ccr,(a6)+
	move.l	#$10,(a5)
	move.l	#$100,4(a5)
	move.l	#$A5A5A500,d1
	move.l	#$0000000f,d1
	move.w	#$1F,ccr
	cmp2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$0000000f,d1
	move.w	#$1F,ccr
	chk2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$00000010,d1
	move.w	#$1F,ccr
	cmp2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$00000010,d1
	move.w	#$1F,ccr
	chk2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$00000100,d1
	move.w	#$1F,ccr
	cmp2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$00000100,d1
	move.w	#$1F,ccr
	chk2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$00000101,d1
	move.w	#$1F,ccr
	cmp2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$00000101,d1
	move.w	#$1F,ccr
	chk2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$ffffffff,d1
	move.w	#$1F,ccr
	cmp2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.l	#$A5A5A500,d1
	move.l	#$ffffffff,d1
	move.w	#$1F,ccr
	chk2.l	(a5),d1
	nop
	move.w	ccr,(a6)+
	move.l	d1,(a6)+
	move.w	#$00,ccr
	trapv
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapt
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapt.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapt.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapf
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapf.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapf.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapeq
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapeq.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapeq.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapne
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapne.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapne.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapvs
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapvs.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapvs.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapmi
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapmi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	trapmi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	traphi
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	traphi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$00,ccr
	traphi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapv
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapt
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapt.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapt.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapf
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapf.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapf.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapeq
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapeq.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapeq.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapne
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapne.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapne.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapvs
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapvs.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapvs.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapmi
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapmi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	trapmi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	traphi
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	traphi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$02,ccr
	traphi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapv
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapt
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapt.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapt.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapf
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapf.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapf.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapeq
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapeq.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapeq.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapne
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapne.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapne.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapvs
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapvs.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapvs.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapmi
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapmi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	trapmi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	traphi
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	traphi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$04,ccr
	traphi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapv
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapt
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapt.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapt.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapf
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapf.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapf.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapeq
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapeq.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapeq.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapne
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapne.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapne.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapvs
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapvs.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapvs.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapmi
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapmi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	trapmi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	traphi
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	traphi.w	#$1234
	nop
	move.w	ccr,(a6)+
	move.w	#$0b,ccr
	traphi.l	#$12345678
	nop
	move.w	ccr,(a6)+
	move.l	#$200,d1
	move.w	#$100,d2
	chk.w	d2,d1
	nop
	move.w	ccr,(a6)+
	move.l	a6,d0			; the log end, so the range check covers it
halt:
	bra.s	halt
unexp:
	bra.s	unexp
trap_h:
	move.w	(sp),(a6)+
	move.l	2(sp),(a6)+
	move.w	6(sp),(a6)+
	move.l	8(sp),(a6)+
	rte

