#!/usr/bin/env python3
"""mk_fpsplib.py <68040.library> <out.bin> <out.inc>

Loads Thomas Richter's 68040.library (MMULib 40.2, 17.8.99 -- the file is
read by path and never copied into this repository) the way LoadSeg would:
the code hunk relocated to LIB_CODE, the data hunk to LIB_DATA, both written
into ONE flat blob that starts at LIB_CODE, for `incbin` at that address in
the FPSP program (tb/fpsp_asm/, plan M10 / the FPSP task of 2026-09-24).

The library carries Motorola's M68040 FPSP.  What the program then runs is
the library's OWN installer (code+$520: record the library base for the
handlers' `([$57a,pc],...)` references, then Supervisor(code+$54e), which
walks the data hunk's table at data+$1C8 and writes the vectors), so the
handlers and the vector numbers come from the library, not from here.

Only this exact file is accepted (md5 below): the entry points are offsets
into it, checked here against the bytes they must hold.
"""
import hashlib, struct, sys

LIB_CODE = 0x10000
LIB_DATA = 0x1A000
MD5 = "a910a87fcfa27cd39c6872184ab7b21f"

# the offsets this program depends on, and the instruction bytes that prove
# they still point where the disassembly said
ENTRY = {
    "LIB_INSTALL": (0x520, "48e7002e284e4bfa0026"),   # movem.l a2/a4-a6,-(a7); movea.l a6,a4; lea $54e(pc),a5
    "LIB_BASEPTR": (0x57a, None),                       # the handlers' library-base pointer (written by the installer)
    "LIB_SYSBASE": (0x4d6, None),                       # SysBase for the handlers' Alert() (written by code+$330)
    "LIB_FLINE":   (0x7c4, "0c6f202c0006"),             # cmpi.w #$202c,6(a7): F-line -> fpsp_unimp
    "LIB_UNSUPP":  (0x15c4, "4e56ff40f327"),            # link a6,#-192; fsave -(a7): fpsp_unsupp
}
VECTAB = 0x1C8    # data hunk: {handler (code-relative, relocated), vector offset, base save offset}...


def parse(d):
    p = 0

    def L():
        nonlocal p
        v = struct.unpack(">I", d[p:p + 4])[0]
        p += 4
        return v
    assert L() == 0x3F3, "not a hunk file"
    while L():
        pass
    L()
    first, last = L(), L()
    sizes = [L() & 0x3FFFFFFF for _ in range(last - first + 1)]
    hunks, cur = [], None
    while p < len(d):
        t = L() & 0x3FFFFFFF
        if t in (0x3E9, 0x3EA):
            n = L()
            cur = {"data": bytearray(d[p:p + n * 4]), "relocs": {}}
            p += n * 4
            hunks.append(cur)
        elif t == 0x3EB:
            cur = {"data": bytearray(L() * 4), "relocs": {}}
            hunks.append(cur)
        elif t == 0x3EC:
            while True:
                cnt = L()
                if cnt == 0:
                    break
                tgt = L()
                cur["relocs"].setdefault(tgt, []).extend(L() for _ in range(cnt))
        elif t == 0x3F2:
            pass
        else:
            raise SystemExit("unexpected hunk type %x" % t)
    for h, s in zip(hunks, sizes):
        h["data"].extend(bytes(max(0, s * 4 - len(h["data"]))))
    return hunks


def main():
    src, obin, oinc = sys.argv[1:4]
    raw = open(src, "rb").read()
    if hashlib.md5(raw).hexdigest() != MD5:
        raise SystemExit("mk_fpsplib: %s is not 68040.library 40.2 (md5 %s)" % (src, MD5))
    code, data = parse(raw)
    base = [LIB_CODE, LIB_DATA]
    for h in (code, data):
        for tgt, offs in h["relocs"].items():
            for o in offs:
                v = struct.unpack(">I", h["data"][o:o + 4])[0] + base[tgt]
                h["data"][o:o + 4] = struct.pack(">I", v)
    for name, (off, want) in ENTRY.items():
        if want and code["data"][off:off + len(want) // 2].hex() != want:
            raise SystemExit("mk_fpsplib: %s at code+$%x does not hold %s" % (name, off, want))
    assert LIB_CODE + len(code["data"]) <= LIB_DATA
    blob = bytearray(code["data"])
    blob.extend(bytes(LIB_DATA - LIB_CODE - len(blob)))
    blob.extend(data["data"])
    open(obin, "wb").write(blob)
    with open(oinc, "w") as f:
        f.write("; generated by mk_fpsplib.py from %s\n" % src)
        f.write("LIB_CODE\tequ\t$%x\nLIB_DATA\tequ\t$%x\nLIB_END\t\tequ\t$%x\n"
                % (LIB_CODE, LIB_DATA, LIB_CODE + len(blob)))
        for name, (off, _) in ENTRY.items():
            f.write("%s\tequ\t$%x\n" % (name, LIB_CODE + off))
        # the vectors the installer will write, for the program's own checks
        p = VECTAB
        n = 0
        while True:
            h = struct.unpack(">I", data["data"][p:p + 4])[0]
            if h == 0:
                break
            vo, _ = struct.unpack(">hh", data["data"][p + 4:p + 8])
            f.write("LIB_VEC%d\tequ\t$%x\t; vector %d\n" % (vo // 4, h, vo // 4))
            p += 8
            n += 1
    print("mk_fpsplib: code $%x-$%x, data $%x-$%x, %d vectors" %
          (LIB_CODE, LIB_CODE + len(code["data"]), LIB_DATA, LIB_DATA + len(data["data"]), n))


if __name__ == "__main__":
    main()
